hw_24
KalchenkoK/FE-Pro pull request #13
Opened 2022-01-10 21:59 UTC by KalchenkoK

2022-01-11 13:40 UTC, ProdanSergey requested changes

2022-01-11 13:40 UTC, ProdanSergey commented on Homework_24/src/app/todo/todo.service.ts
> +export const TodoService = class TodoService {
При чем тут Todo ? у вас было совершенно другое задание.

2022-01-11 13:40 UTC, ProdanSergey commented on Homework_24/src/app/todo/todo.service.ts
> +  async handleGet(value: string): Promise<Todo> {
Это не относится к заданию.

2022-01-11 13:40 UTC, ProdanSergey commented on Homework_24/src/app/todo/todo.service.ts
> +    if(oper === "sum"){
Раздели каждую операцию на соответсвубщий метод.

2022-01-11 13:40 UTC, ProdanSergey commented on Homework_24/src/app/todo/todo.service.ts
> +      const todo = new Todo(`${el1} + ${el2[0]} = ${result}`);
Создай приватный метод this.putLog(func, args, result) и используй его по всему сервису. Этот метод должен форматировать строку в правильном виде перед тем как сохранить в файл.

2022-01-11 13:40 UTC, ProdanSergey commented on Homework_24/src/app/todo/todo.controller.ts
> +export const TodoController = class TodoController {
Проверь все имена. Не копируй бездумно мой код.

2022-01-11 13:40 UTC, ProdanSergey commented on Homework_24/src/app/todo/todo.controller.ts
> +            this.logger.notify("Todo is found:", todo);
!

2022-01-12 17:43 UTC, KalchenkoK commented on Homework_24/src/app/todo/todo.service.ts
> +export const TodoService = class TodoService {
поменял

2022-01-15 16:49 UTC, ProdanSergey approved these changes

2022-01-15 16:49 UTC, ProdanSergey commented on Homework_24/src/app/id/id.service.ts
> +    const result = el2 + el1;
subst это вычитание.

2022-01-15 16:49 UTC, ProdanSergey commented on Homework_24/src/app/id/id.service.ts
> +  private async putLog1(
я бы все таки описывал это все в собственном методел. Для каждой операции отдельно.

2022-01-15 16:49 UTC, ProdanSergey commented on Homework_24/src/app/id/id.service.ts
> +  async handleRes(value: string, oper: string): Promise<void> {
тоже описывал был в собственном методе для каждой операции отдельно

2022-01-15 22:16 UTC, merged