homework_12
KalchenkoK/FE-Pro pull request #3
Opened 2021-11-28 13:56 UTC by KalchenkoK

2021-11-29 10:21 UTC, ProdanSergey requested changes
Если хочешь пересдать, то перед мерджем исправь коменты. Иначе можешь.

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +let date = new Date();
Я уже писал про сохранение даты в глобальной области видимости. Дата важна в момент ее запроса. Нет смысла глобально хранить таймстемп. Обращайся к новому объекту Date каждый раз, когда тебе надо. Или в конкретном вызове синхронной функции.

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/utils.js
> +const archiveFabric = function () {
Для сохранения админа ты должен в фабрику принимать начальное состояния массива entries. Магия сама по себе не происходит.

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +      if (email === "admin@admin.com" && password === "admin") {
Это что такое?) 

Ты должен в любом случае запросить у пользователя данные через STDIN. В методе getAccoutnByEmail найти подходящий акк или вернуть null. А не сравнивать в ручную строки.

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +      } else if (finded) {
Если нашел - вернул то что нашел, а не пересоздаешь экземпляр

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +        return new GuestAccount(email, password);
Тольк ов случае, если нет аккаунта в архиве, ты создаешь новый гест акк, даешь ему данные и сохраняеш в архив, потом возвращаешь уже созданный экземпляр.

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +        } else {
после return не нужно писать else

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +            return this.signUp();
тоже самое

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +            APPLICATION.end();
это тут лишнее, AUTH не должна лезть в APP. Если тебе нужно будет использовать AUTH вдругом приложении, у тебя будет с этим проблема.

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +      const findUserEmail = function (login) {
в отдельный метод

2021-11-29 10:21 UTC, ProdanSergey commented on Homework_12/app/index.js
> +      do {
смысле, ты что 2 раза спрашиваешь юзера что ему делать? 

Ты должен предложить набор операций для юзера относительно его пермишеннов. 

Например: 

у меня ['READ', 'WRITE'] - я могу делать все
у меня ['READ'] - я могу выбрать только просмотр юзеров в архиве или поиск 
у меня ['WRITE'] - я могу только добавлять и удалять

2021-11-29 19:47 UTC, KalchenkoK commented on Homework_12/app/index.js
> +let date = new Date();
поправил

2021-11-29 19:54 UTC, KalchenkoK commented on Homework_12/app/index.js
> +        } else {
поправил

2021-11-29 19:55 UTC, KalchenkoK commented on Homework_12/app/index.js
> +            return this.signUp();
поправил

2021-11-29 20:18 UTC, KalchenkoK commented on Homework_12/app/index.js
> +            APPLICATION.end();
поправил

2021-12-02 19:31 UTC, KalchenkoK commented on Homework_12/app/utils.js
> +const archiveFabric = function () {
accounts.add(new AdminAccount("admin@admin.com", "admin"));

2021-12-03 09:59 UTC, KalchenkoK commented on Homework_12/app/index.js
> +      if (email === "admin@admin.com" && password === "admin") {
const findUserEmail = function (user) {
        return user.email === email && user.password === password;
      };
      user = accounts.find(findUserEmail);     

      if (user) {
        return user;

2021-12-03 10:00 UTC, KalchenkoK commented on Homework_12/app/index.js
> +      } else if (finded) {
поправил

2021-12-03 10:13 UTC, KalchenkoK commented on Homework_12/app/index.js
> +        return new GuestAccount(email, password);
готово

2021-12-03 15:35 UTC, ProdanSergey reviewed
У тебя в пул реквесте 3 разные домашки... Нужно делать реквесты на 1 домашку за раз.

2021-12-03 15:35 UTC, ProdanSergey commented on Homework_12/app/index.js
> +      const email = STDIN.getOperationInput("Enter your email", validateEmail);
В случае singUp важно не допустить регистрации аккаунта с email, который у тебя уже внесен в архив. Иначе у тебя будет 2 копии аккаунта.

2021-12-03 15:35 UTC, ProdanSergey commented on Homework_12/app/index.js
> +          this.signUp();
return забыл

2021-12-03 15:35 UTC, ProdanSergey commented on Homework_12/app/index.js
> +        let confirmed = confirm("Wrong email. Do you want to retry?");
что значит wrong email? ты регистрируешь новый аккаунт, если его STDIN свалидировался, он не может быть wrong.

2021-12-03 15:35 UTC, ProdanSergey commented on Homework_12/app/index.js
> +      if (writePermission) {
сложно... Вместо того, чтобы разделять логику выполнения операций на WRITE, READ. Тебе нужно разделить массив с доступными операциями в зависимости от пермишенов. 

Любая операция выполняется как обычно. Не имеет разницы, есть у тебя пермишены или нет.  А вот какие операции доступны для выполнения, это уже задача пермишинов.

2021-12-03 15:35 UTC, ProdanSergey commented on Homework_12/app/index.js
> +    doOperation_write(index) {
Не правильно. Смотри пред коммент.

2021-12-03 15:35 UTC, ProdanSergey commented on Homework_12/app/index.js
> +    doOperation_read(index) {
Не правильно. Смотри пред коммент.

2021-12-03 15:39 UTC, merged